@echo off
set msas_ver=v1.3
title MSAS MENU By ThexGameLord %msas_ver%

for /f "tokens=1,2 delims==" %%a in (MSAS_conf.ini) do (
if %%a==memuse set memuse=%%b
if %%a==color set color=%%b
)

mode con:cols=70 lines=20
color %color%

if not exist "MSAS_conf.ini" Goto misconf

:MENU
ECHO.
ECHO  ............................................... 
ECHO  MSAS MENU %msas_ver% By ThexGameLord Errorlevel: %errorlevel%
ECHO  ............................................... 
ECHO.
ECHO  1  - install server (changes name of a .jar file to required name)
ECHO  2  - run server
ECHO  3  - Edit Server properties
ECHO  4  - Edit ops
ECHO  5  - Edit whitelist
ECHO  6  - Edit banned-players
ECHO  7  - Edit banned-ips
ECHO  8  - Edit usercache
ECHO  9  - UPDATE Download latest Menu release
ECHO  10 - Here is your server IP [WARNING: SHOWS REAL IP]
ECHO  11 - DEBUG SERVER (if server crashes instantly)
ECHO  12 - SSH
ECHO  13 - RELOAD (reopens MSAS)
ECHO  14 - EXIT
ECHO.

SET /P M=Type any number then press ENTER:
if "%M%"=="" cls & Echo You need to use one of these options. & timeout /t 4 >NUL & cls & Goto menu
IF %M%==1 GOTO INS
IF %M%==2 GOTO RUNSER
IF %M%==3 GOTO SRVPRP
IF %M%==4 GOTO OPS
IF %M%==5 GOTO WLIST
IF %M%==6 GOTO BP
IF %M%==7 GOTO BIP
IF %M%==8 GOTO USRCCH
IF %M%==9 GOTO UPDATE
IF %M%==10 GOTO SIP
IF %M%==11 GOTO DBGSER
IF %M%==12 GOTO SSH_SER
IF %M%==13 GOTO RELOAD
IF %M%==14 GOTO EOF

:INS
del eula.txt
echo #By changing the setting below to TRUE you are indicating your agreement to our EULA (https://account.mojang.com/documents/minecraft_eula).>> eula.txt
echo #github.com/ThexGameLord/MSAS>> eula.txt
echo #Tue Aug 17 15:37:50 BST 2021>> eula.txt
echo eula=TRUE>> eula.txt
echo #Thank you for downloading MSAS if you purchased this then you got scammed, MSAS is free and will always be. - ThexGameLord >> eula.txt
ren *.jar server.jar >NUL
cls
goto menu

:RUNSER
cls
echo Running please wait
java -Xms%memuse%G -Xmx%memuse%G -Dterminal.jline=true -Dterminal.ansi=false -jar server.jar -nogui
cls
goto menu

:SRVPRP
notepad server.properties
cls
goto menu

:OPS
notepad ops.json
cls
goto menu

:WLIST
notepad whitelist.json
cls
goto menu

:BP
notepad banned-players.json
cls
goto menu

:BIP
notepad banned-ips.json
cls
goto menu

:USRCCH
notepad usercache.json
cls
goto menu

:UPDATE
ECHO NOT AVAILABLE DUE TO UPDATE DELETING Other versions of MSAS
timeout /t 2 >NUL
cls
goto menu

:SIP
cls
for /F %%I in ('curl http://ipecho.net/plain') do set pubip=%%I
cls
for /f "tokens=14" %%a in ('ipconfig ^| findstr IPv4') do set _IPaddr=%%a
echo Private IP is: %_IPaddr%
echo Public IP is: %pubip%
echo.
echo Press [Enter] if you are ready to go back to menu 
C:\Windows\System32\timeout.exe 15 >NUL
cls
goto menu

:DBGSER
cls
echo Running Debug Mode please wait
java -Xms%memuse%G -Xmx%memuse%G -Dterminal.jline=true -Dterminal.ansi=false -jar server.jar -nogui
pause
cls
goto menu

:SSH_SER
cls
if not exist "SSH_SERVER.ini" Goto SSH_SERVER_ini_Write
For /f "tokens=2,* delims==" %%a in ('findstr /b /i /l "serverIPAddress" "SSH_SERVER.ini"') do Set "serverIPAddress=%%a"
For /f "tokens=2,* delims==" %%a in ('findstr /b /i /l "USER" "SSH_SERVER.ini"') do Set "USER=%%a"
For /f "tokens=2,* delims==" %%a in ('findstr /b /i /l "PASS" "SSH_SERVER.ini"') do Set "PASS=%%a"
Echo  Server IP: %serverIPAddress% [Connecting]
timeout /t 2 >NUL
cls
color 07
ssh %USER%@%serverIPAddress%
timeout /t 2 >NUL
title MSAS MENU By ThexGameLord %msas_ver%
color %color%
goto menu

:SSH_SERVER_ini_Write
cls
Echo.
Echo  Enter your Server IP address and press enter to continue.
Echo.
Echo  example IP: 127.0.0.1 or 192.168.1.255
Echo.
Echo  Note: You can edit these settings after setting it here.
Echo        By opening the FTP.ini file with notepad.exe
Echo.
Set /p "serverIPAddress=Server IP address: ="
cls
Echo  Enter your Server Username and press enter to continue.
Set /p "USER=SSH USER: ="
if "%serverIPAddress%"=="" Echo The IP address cannot be blank. & cls & Goto SSH_SERVER_ini_Write
(
Echo [Quick SSH settings]
Echo serverIPAddress=%serverIPAddress%
Echo USER=%USER%
Echo #This file was generated by setting up your SSH info in MSAS using option 12
)>SSH_SERVER.ini
goto SSH_SER

:misconf
color 04
echo You dont have a MSAS_conf.ini file [generating one for you now]
timeout 5 >NUL
color 07 >NUL
echo [Server Options] >>MSAS_conf.ini
echo memuse=1 >>MSAS_conf.ini
echo #if you use 1 the server will use -Xms1G -Xmx1G for 1G of memory >>MSAS_conf.ini
echo #Default is 1 >>MSAS_conf.ini
echo [Console Options] >>MSAS_conf.ini
echo color=07 >>MSAS_conf.ini
echo #default is 07 (0 is the background , 7 is the foreground) >>MSAS_conf.ini
goto RELOAD

:RELOAD
start MSAS_MENU_%msas_ver%.bat
exit

:EOF
title Quitting MSAS MENU
cls
echo See you next time.
C:\Windows\System32\timeout.exe 5 >NUL
exit